{
 "title": "K8S Installed Packages Update Cadence",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Deployment Lead Time (days)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  (percentile_cont(0.5) WITHIN GROUP (ORDER BY days_between_vendor_and_deploy)) as \"last 3 months\"\nfrom package_commit_pair_cause_to_deploy\nWHERE deploy_commit_parent_folder='prod'\nand deploy_commit_author_when > now() - interval '3 months'"
    },
    {
     "rawSql": "select \n  (percentile_cont(0.5) WITHIN GROUP (ORDER BY days_between_vendor_and_deploy)) as \"current month\"\nfrom package_commit_pair_cause_to_deploy\nWHERE deploy_commit_parent_folder='prod'\nand date_trunc('month',deploy_commit_author_when)=date_trunc('month', now())"
    }
   ]
  },
  {
   "title": "Patch Deployment Lead Time (Monthly)",
   "type": "graph",
   "description": "Aggregates based on time taken to deploy vendored packages",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n    date_trunc('month',deploy_commit_author_when) as \"time\",\n    min(days_between_vendor_and_deploy),\n    percentile_cont(0.5) WITHIN GROUP (ORDER BY days_between_vendor_and_deploy) as \"median\",\n    max(days_between_vendor_and_deploy)\nfrom package_commit_pair_cause_to_deploy\nWHERE\n  $__timeFilter(deploy_commit_author_when)\ngroup by 1"
    }
   ]
  },
  {
   "title": "Time Taken to Deploy Each Package Update",
   "type": "graph",
   "description": "Based on the time between vendoring and deploying a package. If multiple versions updates have been vendored before deployment, the time to the oldest is taken",
   "gridPos": { "h": 9, "w": 8, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "days" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  deploy_commit_author_when AS \"time\",\n  max(days_between_vendor_and_deploy),\n  deploy_commit_package\nFROM package_commit_pair_cause_to_deploy\nWHERE\n  $__timeFilter(deploy_commit_author_when)\n  and cause_commit_author_when is not null\nGROUP BY 1,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Critically Vulnerable Images (trivy-exporter)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "max_over_time(count(sum(trivy_vulnerabilities{severity=\"CRITICAL\"}) by (image))[$__range:$__interval])",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'critical'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Deployment Frequency (deploys per month)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n    count(distinct (deploy_commit_id || deploy_commit_package))/3 as \"last 3 months\"\nfrom package_commit_pair_cause_to_deploy\nWHERE deploy_commit_parent_folder='prod'\nand deploy_commit_author_when > now() - interval '3 months'"
    },
    {
     "rawSql": "select \n    count(distinct (deploy_commit_id || deploy_commit_package))*(30/extract(day from now())) as \"current month\"\nfrom package_commit_pair_cause_to_deploy\nWHERE deploy_commit_parent_folder='prod'\nand date_trunc('month',deploy_commit_author_when)=date_trunc('month', now())"
    }
   ]
  },
  {
   "title": "Num Patches Deployed (Monthly)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n    date_trunc('month',deploy_commit_author_when) as \"time\",\n    deploy_commit_package,\n    count(distinct (deploy_commit_id || deploy_commit_package)) as \"deploy package patch events\"\nfrom package_commit_pair_cause_to_deploy\nWHERE\n  $__timeFilter(deploy_commit_author_when) \n  and deploy_commit_parent_folder='prod'\ngroup by 1,2\norder by 1,2"
    },
    {
     "rawSql": "select \n    date_trunc('month',deploy_commit_author_when) as \"time\",\n    count(distinct (deploy_commit_id || deploy_commit_package)) as \"total\"\nfrom package_commit_pair_cause_to_deploy\nWHERE\n  $__timeFilter(deploy_commit_author_when) \n  and deploy_commit_parent_folder='prod'\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Vendor Frequency (packages vendored / month)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n    count(distinct (id || package))/3 as \"last 3 months\"\nfrom package_folder_commits\nWHERE parent_folder='automated-vendoring'\nand author_when > now() - interval '3 months'\n"
    },
    {
     "rawSql": "select \n    count(distinct (id || package))*(30/extract(day from now())) as \"current month\"\nfrom package_folder_commits\nWHERE parent_folder='automated-vendoring'\nand date_trunc('month',author_when)=date_trunc('month', now())"
    }
   ]
  },
  {
   "title": "Num Patches Vendored (Monthly)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n    date_trunc('month',author_when) as \"time\",\n    package,\n    count(distinct (id || package)) as \"vendored package events\"\nfrom package_folder_commits\nWHERE\n  $__timeFilter(author_when) \n  and parent_folder='automated-vendoring'\ngroup by 1,2\norder by 1,2"
    },
    {
     "rawSql": "select \n    date_trunc('month',author_when) as \"time\",\n    count(distinct (id || package)) as \"total\"\nfrom package_folder_commits\nWHERE\n  $__timeFilter(author_when) \n  and parent_folder='automated-vendoring'\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Variability of Patch Deployment Lead Time (-2 Months)",
   "type": "bargauge",
   "description": "Time taken to deploy a vendored patch for last month, split out by decile",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  avg(avg_days_between_vendor_and_deploy) as  \"decile\",\n  decile as \"group\"\nfrom packages_summary_deploy_and_cause_timing_decile\nWHERE\n  deploy_month = date_trunc('month', now() - interval '2 month')\nGroup BY 2\nORDER BY 2"
    }
   ]
  },
  {
   "title": "Variability of Patch Deployment Lead Time (Last Month)",
   "type": "bargauge",
   "description": "Time taken to deploy a vendored patch for last month, split out by decile",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  avg(avg_days_between_vendor_and_deploy) as  \"decile\",\n  decile as \"group\"\nfrom packages_summary_deploy_and_cause_timing_decile\nWHERE\n  deploy_month = date_trunc('month', now() - interval '1 month')\nGroup BY 2\nORDER BY 2"
    }
   ]
  },
  {
   "title": "Updates Vendored Per-Package (All Time)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \n    $__timeGroupAlias(author_when,$__interval),\n    package AS metric,\n    count(distinct (id || package)) as \"package vendoring events\"\nfrom package_folder_commits\nWHERE\n  $__timeFilter(author_when) \n  and parent_folder='automated-vendoring'\ngroup by 1,2\norder by 2"
    }
   ]
  },
  {
   "title": "Updates Deployed Per-Package  (All Time)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \n    $__timeGroupAlias(deploy_commit_author_when,$__interval),\n    deploy_commit_package AS metric,\n    count(distinct (deploy_commit_id || deploy_commit_package)) as \"package deployment events\"\nfrom package_commit_pair_cause_to_deploy\nWHERE\n  $__timeFilter(deploy_commit_author_when) \n  and deploy_commit_parent_folder='prod'\n  and cause_commit_parent_folder='automated-vendoring'\ngroup by 1,2\norder by 2"
    }
   ]
  }
 ]
}